global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'article-service'
    metrics_path: /metrics
    static_configs:
      - targets: ['article-service:8080']

#  - job_name: 'comment-service'
 #   metrics_path: /metrics
  #  static_configs:
   #   - targets: ['comment-service:8081']
