global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'article-service'
    static_configs:
      - targets: ['article-service:8080']

  - job_name: 'comment-service'
    static_configs:
      - targets: ['comment-service:8081']
