###version: "3.9"
###services:
###  article-service:
###    build: .
###    ports:
###      - "8080:8080"
###    environment:
###      ConnectionStrings__Default: "Server=${DB_HOST},${DB_PORT};Database=${DB_NAME};User ID=${DB_USER};Password=${DB_PASSWORD};Encrypt=True;TrustServerCertificate=True"
###

services:
  db:
    image: "${DB_IMAGE}"
    platform: "${DB_PLATFORM}"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "${DB_PASSWORD}"
    ports:
      - "${DB_PORT}:1433"
    volumes:
      - sqldata:/var/opt/mssql

  article-service:
    build: .
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ConnectionStrings__Default: "Server=${DB_HOST},${DB_PORT};Database=${DB_NAME};User ID=sa;Password=${DB_PASSWORD};Encrypt=True;TrustServerCertificate=True;"
    ports:
      - "8080:8080"
    depends_on:
      - db
    restart: unless-stopped

volumes:
  sqldata: